version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; uvicorn financial.api:app --host 0.0.0.0'
    volumes:
      - .:/app
    expose:
      - 8000
    ports:
      - 5000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@database:5432/fastapi_traefik
      - API_KEY=<Your-AlphaVantage-API-Key>
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik


volumes:
  postgres_data:

